[feat-7] Token Location Cookie Parsing 지원
iml1111/django-jwt-extended pull request #15
Opened 2022-07-31 11:08 UTC by akshxl09

2022-08-01 05:05 UTC, iml1111 requested changes
다 잘짜여져 있는데, 간과한 점은 리프레시 쿠키를 간과한 것 같음.

백단으로부터 프론트단이 토큰을 총 2개를 리턴받게 될텐데 각각의 쿠키에 대한 이름을 설정할 수 있어야 함.
해당 쿠키에 secure 옵션이 걸려 있으면 프론트는 해당 쿠키에 일절 접근할 수 없기 때문에 꼭 해당 설정이 필요할듯.

2022-08-01 05:05 UTC, iml1111 commented on django_jwt_extended/apps.py
> +        self.token_cookie_name = data.token_cookie_name
액세스 쿠키 이름, 리프레시 쿠키 이름을 나눠야 하지 않을까 싶습니다

2022-08-01 06:25 UTC, akshxl09 commented on django_jwt_extended/apps.py
> +        self.token_cookie_name = data.token_cookie_name
아 secure 옵션으로 인해 쿠키조작이 불가능한거였구나

2022-08-01 16:00 UTC, akshxl09 commented on django_jwt_extended/tokens.py
> +
refresh를 받아서 구분할 수 있도록 만들어봤읍니다. @iml1111

2022-08-02 05:58 UTC, iml1111 requested changes

2022-08-02 05:58 UTC, iml1111 commented on django_jwt_extended/apps.py
> +        self.refresh_cookie_name = data.refresh_cookie_name
access_token_cookie_name
refresh_token_cookie_name
으로 하는게 어떨까 싶음

2022-08-02 05:58 UTC, iml1111 commented on django_jwt_extended/apps.py
> +        self.refresh_cookie_name = data.refresh_cookie_name
그 외에 관련 코드 부분도 마찬가지로 ㅇㅇ

2022-08-02 05:58 UTC, iml1111 commented on django_jwt_extended/tokens.py
> +
지금와서 보니까 COOKIES가 get 메소드를 가지고 있다면 아래와 같이 작성해볼 수도 있을듯.
```python
if not refresh:
    return request.COOKIES.get(config.access_cookie_name), location
elif refresh:
    return request.COOKIES.get(config.refresh_cookie_name), location
```
위에 headers도 똑같은 방식으로 가능할 것 같기도 하고?

2022-08-03 07:31 UTC, iml1111 approved these changes
LGTM

2022-08-03 07:32 UTC, merged